# ---------- Industry Mapping ----------
industry_mapping = {
    "Food & Agriculture": {
        "Crop farm": "Crop farm",
        "Livestock farm": "Livestock farm",
        "Fishery": "Fishery",
        "Agricultural machinery supplier": "Agricultural machinery supplier",
        "Food processing company": "Food processing company",
        "Dairy producer": "Dairy producer",
        "Meat processing plant": "Meat processing plant",
        "Bakery": "Bakery",
        "Beverage company": "Beverage company",
        "Fertilizer manufacturer": "Fertilizer manufacturer",
        "Tree farm": "Tree farm",
        "Food machinery supplier": "Food machinery supplier",
        "Bakery equipment": "Bakery equipment",
        "Agricultural product wholesaler": "Agricultural product wholesaler"
    },
    "Business Services": {
        "Corporate office": "Corporate office",
        "Business center": "Business center",
        "Consulting firm": "Consulting firm",
        "Law firm": "Law firm",
        "Accounting firm": "Accounting firm",
        "Marketing agency": "Marketing agency",
        "Recruitment agency": "Recruitment agency",
        "Research institute": "Research institute",
        "Bank": "Bank",
        "Insurance company": "Insurance company",
        "Asset management firm": "Asset management firm",
        "Venture capital firm": "Venture capital firm",
        "Fintech startup": "Fintech startup",
        "Estate appraiser": "Estate appraiser",
        "Investment company": "Investment company",
        "Property management company": "Property management company",
        "Importer": "Importer",
        "Import export company": "Import export company",
        "Company": "Company",
        "Coworking space": "Coworking space",
        "Professional organizer": "Professional organizer",
        "Advertising agency": "Advertising agency",
        "Government office": "Government office",
        "Local government office": "Local government office"
    },
    "Chemicals, Pharmaceuticals & Plastics": {
        "Chemical manufacturer": "Chemical manufacturer",
        "Industrial chemicals wholesaler": "Industrial chemicals wholesaler",
        "Pharmaceutical company": "Pharmaceutical company",
        "Biotechnology firm": "Biotechnology firm",
        "Chemical industry": "Chemical industry",
        "Plastic fabrication company": "Plastic fabrication company",
        "Ceramic manufacturer": "Ceramic manufacturer",
        "Foam rubber producer": "Foam rubber producer"
    },
    "Construction": {
        "Construction contractor": "Construction contractor",
        "Construction and maintenance office": "Construction and maintenance office",
        "Construction material supplier": "Construction material supplier",
        "Building materials supplier": "Building materials supplier",
        "Architecture firm": "Architecture firm",
        "Cement manufacturer": "Cement manufacturer",
        "Architect": "Architect",
        "Interior designer": "Interior designer",
        "Property developer": "Property developer",
        "Real estate agency": "Real estate agency",
        "Construction equipment supplier": "Construction equipment supplier",
        "Building firm": "Building firm",
        "Construction material wholesaler": "Construction material wholesaler",
        "Landscaping supply store": "Landscaping supply store",
        "Paint store": "Paint store",
        "Building materials store": "Building materials store",
        "Wholesaler": "Wholesaler",
        "Construction company": "Construction company",
        "Bathroom supply store": "Bathroom supply store",
        "General contractor": "General contractor",
        "Masonry supply store": "Masonry supply store",
        "Hardware store": "Hardware store",
        "Civil engineering company": "Civil engineering company",
        "Home builder": "Home builder",
        "Scaffolding rental service": "Scaffolding rental service",
        "Welding supply store": "Welding supply store",
        "Roofing supply store": "Roofing supply store",
        "Civil engineer": "Civil engineer",
        "Metal construction company": "Metal construction company",
        "Concrete product supplier": "Concrete product supplier",
        "Tile store": "Tile store",
        "Woodworking supply store": "Woodworking supply store",
        "Building materials market": "Building materials market",
        "Contractor": "Contractor",
        "Road construction company": "Road construction company",
        "Cement supplier": "Cement supplier",
        "Ready mix concrete supplier": "Ready mix concrete supplier",
        "Marine supply store": "Marine supply store",
        "Ceramics wholesaler": "Ceramics wholesaler",
        "Do-it-yourself shop": "Do-it-yourself shop",
        "Finishing materials supplier": "Finishing materials supplier",
        "Plumbing supply store": "Plumbing supply store",
        "Carpet store": "Carpet store",
        "Tool store": "Tool store",
        "Demolition contractor": "Demolition contractor",
        "Home improvement store": "Home improvement store",
        "Masonry contractor": "Masonry contractor",
        "Fence supply store": "Fence supply store",
        "Flooring store": "Flooring store",
        "Insulation materials store": "Insulation materials store",
        "Condominium complex": "Condominium complex",
        "Steel construction company": "Steel construction company",
        "Carpenter": "Carpenter",
        "Iron steel contractor": "Iron steel contractor",
        "Wood and laminate flooring supplier": "Wood and laminate flooring supplier",
        "Aluminum supplier": "Aluminum supplier",
        "Lumber store": "Lumber store",
        "Waterproofing service": "Waterproofing service",
        "Tool rental service": "Tool rental service",
        "PVC industry": "PVC industry",
        "Plastic fabrication company": "Plastic fabrication company",
        "Remodeler": "Remodeler",
        "Insulation contractor": "Insulation contractor",
        "Screen printing supply store": "Screen printing supply store",
        "Painting": "Painting",
        "Kitchen remodeler": "Kitchen remodeler",
        "Flooring contractor": "Flooring contractor",
        "Logging contractor": "Logging contractor",
        "Asphalt contractor": "Asphalt contractor",
        "Paving contractor": "Paving contractor",
        "Earth works company": "Earth works company",
        "Millwork shop": "Millwork shop",
        "Chemical plant": "Chemical plant",
        "Dry wall supply store": "Dry wall supply store",
        "Architectural designer": "Architectural designer",
        "Stationery wholesaler": "Stationery wholesaler",
        "Dry wall contractor": "Dry wall contractor",
        "Topography company": "Topography company",
        "Custom home builder": "Custom home builder",
        "Renovation contractor": "Renovation contractor",
        "Brick manufacturer": "Brick manufacturer",
        "Wallpaper store": "Wallpaper store",
        "Prefabricated house companies": "Prefabricated house companies",
        "Plywood supplier": "Plywood supplier",
        "Construction machine dealer": "Construction machine dealer",
        "Rolled metal products supplier": "Rolled metal products supplier",
        "Interior architect office": "Interior architect office",
        "Engineering consultant": "Engineering consultant",
        "Building society": "Building society",
        "Fire protection system supplier": "Fire protection system supplier",
        "Concrete contractor": "Concrete contractor",
        "Road construction machine repair service": "Road construction machine repair service",
        "Plast window store": "Plast window store",
        "Concrete factory": "Concrete factory",
        "Fountain contractor": "Fountain contractor",
        "Curtain supplier and maker": "Curtain supplier and maker",
        "Bricklayer": "Bricklayer",
        "Quarry": "Quarry",
        "Dock builder": "Dock builder",
        "Property maintenance": "Property maintenance",
        "Roofing contractor": "Roofing contractor",
        "Stucco contractor": "Stucco contractor",
        "Deck builder": "Deck builder",
        "Building consultant": "Building consultant",
        "Interior designer": "Interior designer",
        "Builder": "Builder",
        "Fire protection equipment supplier": "Fire protection equipment supplier",
        "Stair contractor": "Stair contractor",
        "Log home builder": "Log home builder",
        "Garage door supplier": "Garage door supplier",
        "Landscape architect": "Landscape architect",
        "Landscaper": "Landscaper",
        "Tree service": "Tree service",
        "Portable building manufacturer": "Portable building manufacturer",
        "Window supplier": "Window supplier",
        "PVC windows supplier": "PVC windows supplier",
        "Door shop": "Door shop",
        "Interior door shop": "Interior door shop",
        "Door manufacturer": "Door manufacturer",
        "Door supplier": "Door supplier",
        "Fireplace store": "Fireplace store",
        "Crane dealer": "Crane dealer",
        "Cabinet maker": "Cabinet maker",
        "Cabinet store": "Cabinet store",
        "Handyman/Handywoman/Handyperson": "Handyman/Handywoman/Handyperson",
        "Shopfitter": "Shopfitter"
    },
    "Healthcare": {
        "Private hospital": "Private hospital",
        "Maternity hospital": "Maternity hospital",
        "Hospital": "Hospital",
        "General hospital": "General hospital",
        "Pharmacy": "Pharmacy",
        "Medical group": "Medical group",
        "Medical supply store": "Medical supply store",
        "Association / Organization": "Association / Organization",
        "Non-profit organization": "Non-profit organization",
        "Maternity store": "Maternity store",
        "Pregnancy care center": "Pregnancy care center",
        "University hospital": "University hospital",
        "Health and beauty shop": "Health and beauty shop",
        "Midwife": "Midwife",
        "Department store": "Department store", 
        "Fertility clinic": "Fertility clinic",
        "Reproductive health clinic": "Reproductive health clinic",
        "Women's health clinic": "Women's health clinic",
        "Community health centre": "Community health centre",
        "Volunteer organization": "Volunteer organization",
        "Delivery Service": "Delivery Service",
        "Homeopathic pharmacy": "Homeopathic pharmacy",
        "Herbal medicine store": "Herbal medicine store",
        "Nutritionist": "Nutritionist",
        "Medical equipment supplier": "Medical equipment supplier",
        "Home health care service": "Home health care service",
        "Parapharmacy": "Parapharmacy",
        "Obstetrician-gynecologist": "Obstetrician-gynecologist",
        "Health consultant": "Health consultant",
        "Cosmetics wholesaler": "Cosmetics wholesaler",
        "Medical clinic": "Medical clinic",
        "Medical Center": "Medical Center",
        "Government hospital": "Government hospital",
        "Faculty of pharmacy": "Faculty of pharmacy",
        "Pharmaceutical wholesaler": "Pharmaceutical wholesaler",
    },
    "Education, Training & Non-profit": {
        "School": "School",
        "E-learning provider": "E-learning provider",
        "Art school": "Art school",
        "Non-profit organization": "Non-profit organization"
    },
    "Electrical & Electronics": {
        "Electrical products wholesaler": "Electrical products wholesaler",
        "Electrical equipment supplier": "Electrical equipment supplier",
        "Electrical engineer": "Electrical engineer",
        "Hardware manufacturer": "Hardware manufacturer",
        "Semiconductor manufacturer": "Semiconductor manufacturer",
        "Telecommunications equipment supplier": "Telecommunications equipment supplier",
        "Telecommunications service provider": "Telecommunications service provider",
        "Telecommunications contractor": "Telecommunications contractor",
        "Cable company": "Cable company",
        "Security system supplier": "Security system supplier",
        "Electrical appliance wholesaler": "Electrical appliance wholesaler",
        "Electrical supply store": "Electrical supply store",
        "Electronics wholesaler": "Electronics wholesaler",
        "Electronics store": "Electronics store",
        "Computer store": "Computer store",
        "Locks supplier": "Locks supplier"
    },
    "Energy, Environment & Resources": {
        "Oil refinery": "Oil refinery",
        "Oil & natural gas company": "Oil & natural gas company",
        "Oil field equipment supplier": "Oil field equipment supplier",
        "Oil wholesaler": "Oil wholesaler",
        "Diesel fuel supplier": "Diesel fuel supplier",
        "Oil store": "Oil store",
        "Oilfield": "Oilfield",
        "Solar energy company": "Solar energy company",
        "Solar energy system service": "Solar energy system service",
        "Solar energy equipment supplier": "Solar energy equipment supplier",
        "Solar hot water system supplier": "Solar hot water system supplier",
        "Electric utility company": "Electric utility company",
        "Power station": "Power station",
        "Energy equipment and solutions": "Energy equipment and solutions",
        "Coal mining": "Coal mining",
        "Coal processing": "Coal processing",
        "Wind energy company": "Wind energy company",
        "Hydropower plant": "Hydropower plant",
        "Diesel engine dealer": "Diesel engine dealer",
        "Forestry service": "Forestry service"
    },
    "IT & Internet": {
        "Software company": "Software company",
        "IT services provider": "IT services provider",
        "E-commerce platform": "E-commerce platform",
        "Cybersecurity firm": "Cybersecurity firm",
        "AI solutions provider": "AI solutions provider",
        "E-commerce service": "E-commerce service",
        "Scientific equipment supplier": "Scientific equipment supplier"
    },
    "Leisure & Tourism": {
        "TV broadcaster": "TV broadcaster",
        "Film production company": "Film production company",
        "Music label": "Music label",
        "Game developer": "Game developer",
        "Creative agency": "Creative agency",
        "Performing arts theater": "Performing arts theater",
        "Entertainer": "Entertainer",
        "Pottery classes": "Pottery classes",
        "Museum": "Museum",
        "Gym": "Gym",
        "Ski rental service": "Ski rental service",
        "Brewery": "Brewery",
        "Brewpub": "Brewpub",
        "Cafe": "Cafe",
        "Restaurant": "Restaurant"
    },
    "Manufacturing, Industry, Metal & Engineering": {
        "Industrial equipment supplier": "Industrial equipment supplier",
        "Equipment rental agency": "Equipment rental agency",
        "Manufacturer": "Manufacturer",
        "Shipyard": "Shipyard",
        "Shipbuilding and repair company": "Shipbuilding and repair company",
        "Metal processing": "Metal processing",
        "Steel manufacturer": "Steel manufacturer",
        "Car manufacturer": "Car manufacturer",
        "Aerospace company": "Aerospace company",
        "Defense contractor": "Defense contractor",
        "Automation solutions provider": "Automation solutions provider",
        "Machining manufacturer": "Machining manufacturer",
        "Tool manufacturer": "Tool manufacturer",
        "Paint manufacturer": "Paint manufacturer",
        "Auto painting": "Auto painting",
        "Metal workshop": "Metal workshop",
        "Machine shop": "Machine shop",
        "Machinery parts manufacturer": "Machinery parts manufacturer",
        "Toolroom": "Toolroom",
        "Metalwork": "Metalwork",
        "Equipment supplier": "Equipment supplier",
        "Tool store": "Tool store",
        "Tool repair shop": "Tool repair shop",
        "Metal supplier": "Metal supplier",
        "Metal fabricator": "Metal fabricator",
        "Steel fabricator": "Steel fabricator",
        "Metal machinery supplier": "Metal machinery supplier",
        "Foundry": "Foundry",
        "Mechanical plant": "Mechanical plant",
        "Metallurgy company": "Metallurgy company",
        "Laser cutting service": "Laser cutting service",
        "Laser equipment supplier": "Laser equipment supplier",
        "Fastener supplier": "Fastener supplier",
        "Bearing supplier": "Bearing supplier",
        "Pallet supplier": "Pallet supplier"
    },
    "Minerals": {
        "Mining company": "Mining company",
        "Mineral processing": "Mineral processing"
    },
    "Paper, Printing & Publishing": {
        "Paper mill": "Paper mill",
        "Packaging company": "Packaging company",
        "Printing service": "Printing service",
        "Printing equipment supplier": "Printing equipment supplier",
        "Digital printing service": "Digital printing service",
        "Packaging supply store": "Packaging supply store"
    },
    "Retail & Traders": {
        "Retail chain": "Retail chain",
        "Childrens store": "Childrens store",
        "Consumer electronics retailer": "Consumer electronics retailer",
        "Luxury brand": "Luxury brand",
        "Household products manufacturer": "Household products manufacturer",
        "Bag shop": "Bag shop",
        "Shoe store": "Shoe store",
        "Hobby store": "Hobby store",
        "Painting studio": "Painting studio",
        "Art supply store": "Art supply store",
        "Stationery store": "Stationery store",
        "Paintings store": "Paintings store",
        "Model shop": "Model shop",
        "Steel distributor": "Steel distributor",
        "Pipe supplier": "Pipe supplier",
        "Trading firm": "Trading firm",
        "Store": "Store",
        "Do-it-yourself shop": "Do-it-yourself shop",
        "Book store": "Book store",
        "Craft store": "Craft store",
        "Outlet store": "Outlet store",
        "Handicraft": "Handicraft",
        "Warehouse store": "Warehouse store",
        "Showroom": "Showroom",
        "Furniture store": "Furniture store",
        "Industrial supermarket": "Industrial supermarket",
        "Kitchen furniture store": "Kitchen furniture store",
        "Sofa store": "Sofa store",
        "Bar restaurant furniture store": "Bar restaurant furniture store",
        "Appliance store": "Appliance store",
        "Mattress store": "Mattress store",
        "Bedroom furniture store": "Bedroom furniture store",
        "Outdoor furniture store": "Outdoor furniture store",
        "Used furniture store": "Used furniture store",
        "Furniture rental service": "Furniture rental service",
        "Furniture repair shop": "Furniture repair shop",
        "Furniture wholesaler": "Furniture wholesaler",
        "Garden furniture shop": "Garden furniture shop",
        "Gift wrap store": "Gift wrap store",
        "Shelving store": "Shelving store",
        "School supply store": "School supply store",
        "Office supply store": "Office supply store",
        "Shop supermarket furniture store": "Shop supermarket furniture store",
        "Bedding store": "Bedding store",
        "Mirror shop": "Mirror shop",
        "Safe & vault shop": "Safe & vault shop",
        "Toy manufacturer": "Toy manufacturer",
        "Confectionery store": "Confectionery store",
        "Florist": "Florist",
        "Gift shop": "Gift shop",
        "Sporting goods store": "Sporting goods store",
        "Baby store": "Baby store",
        "Children's clothing store": "Children's clothing store",
        "Home goods store": "Home goods store",
        "Fabric store": "Fabric store",
        "Clothing store": "Clothing store",
        "Baby clothing store": "Baby clothing store",
        "Hypermarket": "Hypermarket",
        "Cosmetics store": "Cosmetics store",
        "Drug store": "Drug store",
        "Leather goods store": "Leather goods store",
        "Handicraft": "Handicraft",
        "Flower delivery": "Flower delivery",
        "Charity": "Charity",
        "Natural goods store": "Natural goods store",
        "Book store": "Book store",
        "Toy store": "Toy store",
        "Religious goods store": "Religious goods store",
        "Shopping mall": "Shopping mall",
        "Store": "Store",
        "Supermarket": "Supermarket",
        "Children's furniture store": "Children's furniture store",
        "Women's clothing store": "Women's clothing store",
        "Embroidery shop": "Embroidery shop",
        "Clothing supplier": "Clothing supplier",
        "Manufacturer": "Manufacturer",
        "Gift shop": "Gift shop",
        "Pet store": "Pet store",
        "Gift basket store": "Gift basket store",
        "Organic food store": "Organic food store",

    },
    "Textiles, Clothing, Leather, Watchmaking, Jewellery": {
        "Textile manufacturer": "Textile manufacturer",
        "Clothing store": "Clothing store",
        "Knitwear manufacturer": "Knitwear manufacturer",
        "Sewing shop": "Sewing shop",
        "Sewing company": "Sewing company",
        "Fabric product manufacturer": "Fabric product manufacturer",
        "Textile mill": "Textile mill"
    },
    "Transport & Logistics": {
        "Distribution service": "Distribution service",
        "Shipping company": "Shipping company",
        "Airline": "Airline",
        "Railway operator": "Railway operator",
        "Trucking company": "Trucking company",
        "Warehouse": "Warehouse",
        "Courier service": "Courier service"
    },
    "Real Estate": {
        "Real estate developer": "Real estate developer",
        "Real Estate Agency": "Real Estate Agency",
        "Real estate": "Real estate",
        "Condominium complex": "Condominium complex",
        "Apartment complex": "Apartment complex",
        "Lodging": "Lodging",
        "Guest house": "Guest house",
        "Hotel": "Hotel"
    }
}
