# ---------- Industry Mapping ----------
industry_mapping = {
    "Food & Agriculture": {
        "Crop farm": "Crop farm",
        "Livestock farm": "Livestock farm",
        "Fishery": "Fishery",
        "Agricultural machinery supplier": "Agricultural machinery supplier",
        "Food processing company": "Food processing company",
        "Dairy producer": "Dairy producer",
        "Meat processing plant": "Meat processing plant",
        "Bakery": "Bakery",
        "Beverage company": "Beverage company",
        "Beverage distributor": "Beverage distributor",
        "Fertilizer manufacturer": "Fertilizer manufacturer",
        "Tree farm": "Tree farm",
        "Food machinery supplier": "Food machinery supplier",
        "Bakery equipment": "Bakery equipment",
        "Agricultural product wholesaler": "Agricultural product wholesaler",
        "Wine store": "Wine store",
        "Dairy": "Dairy",
        "Cheese shop": "Cheese shop",
        "Wine bar": "Wine bar",
        "Butcher shop deli": "Butcher shop deli",
        "Butcher shop": "Butcher shop",
        "Food products supplier": "Food products supplier",
        "Cake shop": "Cake shop",
        "Chocolate artisan": "Chocolate artisan",
        "Chocolate shop": "Chocolate shop",
        "Cookie shop": "Cookie shop",
        "Vitamin & supplements store": "Vitamin & supplements store",
        "Kitchen supply store": "Kitchen supply store",
        "Food manufacturer": "Food manufacturer",
        "Ice supplier": "Ice supplier",
        "Donut shop": "Donut shop",
        "Wholesale bakery": "Wholesale bakery",
        "Pastry shop": "Pastry shop",
        "Gourmet grocery store": "Gourmet grocery store",
        "Grocery store": "Grocery store",
        "Sandwich shop": "Sandwich shop",
        "Fast food restaurant": "Fast food restaurant",
        "Italian restaurant": "Italian restaurant",
        "Animal feed store": "Animal feed store",
        "Feed manufacturer": "Feed manufacturer",
        "Truck farmer": "Truck farmer",
        "Frozen food store": "Frozen food store",
        "Pasta shop": "Pasta shop",
        "Spice store": "Spice store",
        "Caterer": "Caterer",
        "Patisserie": "Patisserie",
        "Wedding bakery": "Wedding bakery",
        "Indian grocery store": "Indian grocery store",
        "Liquor store": "Liquor store",
        "Pie shop": "Pie shop",
        "Tea store": "Tea store",
        "French restaurant": "French restaurant",
        "Pizza restaurant": "Pizza restaurant",
        "Meat wholesaler": "Meat wholesaler",
        "Meat processor": "Meat processor",
        "Meat products store": "Meat products store",
        "Seafood wholesaler": "Seafood wholesaler",
        "Fresh food market": "Fresh food market",
        "Wine cellar": "Wine cellar",
        "Winery": "Winery",
        "Vineyard": "Vineyard",
        "Food industry": "Food industry",
        "Candy store": "Candy store",
        "Agricultural cooperative": "Agricultural cooperative",
        "Produce wholesaler": "Produce wholesaler",
        "Deli Shop": "Deli Shop",
        "Deli": "Deli",
        "Grocery delivery service": "Grocery delivery service",
        "Farm": "Farm",
        "Dairy farm": "Dairy farm",
        "Italian grocery store": "Italian grocery store",
        "Wine wholesaler and importer": "Wine wholesaler and importer",
        "Organic shop": "Organic shop",
        "Farm equipment supplier": "Farm equipment supplier",
        "Catering food and drink supplier": "Catering food and drink supplier",
        "Cheese manufacturer": "Cheese manufacturer",
        "Food producer": "Food producer",
        "Wholesale grocer": "Wholesale grocer",
        "Soft drinks shop": "Soft drinks shop",
        "Snack bar": "Snack bar",
        "Pie shop": "Pie shop",
        "Ice cream shop": "Ice cream shop",
        "Baking supply store": "Baking supply store",
        "Agricultural association": "Agricultural association",
        "Food manufacturing supply": "Food manufacturing supply",
        "Fruit and vegetable store": "Fruit and vegetable store",
        "Greengrocer": "Greengrocer",
        "Seed supplier": "Seed supplier",
        "Fruit wholesaler": "Fruit wholesaler",
        "Food processing equipment": "Food processing equipment",
        "Food broker": "Food broker",
        "Olive oil manufacturer": "Olive oil manufacturer",
        "Confectionery wholesaler": "Confectionery wholesaler",
        "Coffee roasters": "Coffee roasters",
        "Health food store": "Health food store",
        "Plant nursery": "Plant nursery",
        "Organic farm": "Organic farm",
        "Meat packer": "Meat packer",
        "Coffee wholesaler": "Coffee wholesaler",
        "Mineral water wholesaler": "Mineral water wholesaler"
    },
    "Business Services": {
        "Corporate office": "Corporate office",
        "Business center": "Business center",
        "Consulting firm": "Consulting firm",
        "Law firm": "Law firm",
        "Accounting firm": "Accounting firm",
        "Marketing agency": "Marketing agency",
        "Recruitment agency": "Recruitment agency",
        "Research institute": "Research institute",
        "Bank": "Bank",
        "Insurance company": "Insurance company",
        "Asset management firm": "Asset management firm",
        "Venture capital firm": "Venture capital firm",
        "Fintech startup": "Fintech startup",
        "Estate appraiser": "Estate appraiser",
        "Investment company": "Investment company",
        "Property management company": "Property management company",
        "Importer": "Importer",
        "Import export company": "Import export company",
        "Company": "Company",
        "Coworking space": "Coworking space",
        "Professional organizer": "Professional organizer",
        "Advertising agency": "Advertising agency",
        "Government office": "Government office",
        "Local government office": "Local government office",
        "Event planner": "Event planner",
        "Business management consultant": "Business management consultant",
        "Executive search firm": "Executive search firm",
        "Business networking company": "Business networking company",
        "Consultant": "Consultant",
        "Market researcher": "Market researcher",
        "Research and product development": "Research and product development",
        "Certified public accountant": "Certified public accountant",
        "Chartered accountant": "Chartered accountant",
        "Economic consultant": "Economic consultant",
        "Marketing consultant": "Marketing consultant",
        "Human resource consulting": "Human resource consulting",
        "Business broker": "Business broker",
        "Investment service": "Investment service",
        "Business to business service": "Business to business service",
        "Business development service": "Business development service",
        "Temp agency": "Temp agency",
        "Employment agency": "Employment agency",
        "Appraiser": "Appraiser",
        "Real estate appraiser": "Real estate appraiser",
        "Real estate consultant": "Real estate consultant",
        "Accountant": "Accountant",
        "Website designer": "Website designer",
        "Computer support and services": "Computer support and services",
        "Computer consultant": "Computer consultant",
        "Computer security service": "Computer security service",
        "Internet marketing service": "Internet marketing service",
        "Data center": "Data center",
        "Administrative attorney": "Administrative attorney",
        "Urban planning department": "Urban planning department",
        "Party equipment rental service": "Party equipment rental service",
        "Graphic designer": "Graphic designer",
        "Shredding service": "Shredding service",
        "Meeting planning service": "Meeting planning service",
        "Database management company": "Database management company",
        "Attorney": "Attorney",
        "Visa and passport office": "Visa and passport office",
        "Classified ads newspaper publisher": "Classified ads newspaper publisher",
        "Council": "Council",
        "City government office": "City government office",
        "Web hosting company": "Web hosting company",
        "House clearance service": "House clearance service",
        "Driving test center": "Driving test center",
        "International trade consultant": "International trade consultant",
        "Branding agency": "Branding agency",
        "Financial consultant": "Financial consultant",
        "Call center": "Call center",
        "Office space rental agency": "Office space rental agency",
        "Recruiter": "Recruiter",
        "Paralegal services provider": "Paralegal services provider",
        "Holding company": "Holding company",
        "Exhibition and trade centre": "Exhibition and trade centre",
        "Money order service": "Money order service"
    },
    "Chemicals, Pharmaceuticals & Plastics": {
        "Chemical manufacturer": "Chemical manufacturer",
        "Industrial chemicals wholesaler": "Industrial chemicals wholesaler",
        "Pharmaceutical company": "Pharmaceutical company",
        "Biotechnology firm": "Biotechnology firm",
        "Chemical industry": "Chemical industry",
        "Plastic fabrication company": "Plastic fabrication company",
        "Ceramic manufacturer": "Ceramic manufacturer",
        "Foam rubber producer": "Foam rubber producer",
        "Chemical plant": "Chemical plant",
        "Biotechnology company": "Biotechnology company",
        "Cosmetics industry": "Cosmetics industry",
        "Cosmetic products manufacturer": "Cosmetic products manufacturer",
        "Chemical wholesaler": "Chemical wholesaler",
        "Plastic products wholesaler": "Plastic products wholesaler",
        "Plastic supplier": "Plastic supplier",
        "Foam rubber supplier": "Foam rubber supplier",
        "Plastic resin manufacturer": "Plastic resin manufacturer",
        "Plastic injection molding service": "Plastic injection molding service",
        "Chemistry lab": "Chemistry lab"
    },
    "Construction": {
        "Construction contractor": "Construction contractor",
        "Construction and maintenance office": "Construction and maintenance office",
        "Construction material supplier": "Construction material supplier",
        "Building materials supplier": "Building materials supplier",
        "Architecture firm": "Architecture firm",
        "Cement manufacturer": "Cement manufacturer",
        "Architect": "Architect",
        "Interior designer": "Interior designer",
        "Property developer": "Property developer",
        "Real estate agency": "Real estate agency",
        "Construction equipment supplier": "Construction equipment supplier",
        "Building firm": "Building firm",
        "Construction material wholesaler": "Construction material wholesaler",
        "Landscaping supply store": "Landscaping supply store",
        "Paint store": "Paint store",
        "Building materials store": "Building materials store",
        "Construction company": "Construction company",
        "Bathroom supply store": "Bathroom supply store",
        "General contractor": "General contractor",
        "Masonry supply store": "Masonry supply store",
        "Hardware store": "Hardware store",
        "Civil engineering company": "Civil engineering company",
        "Home builder": "Home builder",
        "Scaffolding rental service": "Scaffolding rental service",
        "Welding supply store": "Welding supply store",
        "Roofing supply store": "Roofing supply store",
        "Civil engineer": "Civil engineer",
        "Metal construction company": "Metal construction company",
        "Concrete product supplier": "Concrete product supplier",
        "Tile store": "Tile store",
        "Woodworking supply store": "Woodworking supply store",
        "Building materials market": "Building materials market",
        "Contractor": "Contractor",
        "Road construction company": "Road construction company",
        "Cement supplier": "Cement supplier",
        "Ready mix concrete supplier": "Ready mix concrete supplier",
        "Marine supply store": "Marine supply store",
        "Ceramics wholesaler": "Ceramics wholesaler",
        "Do-it-yourself shop": "Do-it-yourself shop",
        "Finishing materials supplier": "Finishing materials supplier",
        "Plumbing supply store": "Plumbing supply store",
        "Carpet store": "Carpet store",
        "Tool store": "Tool store",
        "Demolition contractor": "Demolition contractor",
        "Home improvement store": "Home improvement store",
        "Masonry contractor": "Masonry contractor",
        "Fence supply store": "Fence supply store",
        "Flooring store": "Flooring store",
        "Insulation materials store": "Insulation materials store",
        "Condominium complex": "Condominium complex",
        "Steel construction company": "Steel construction company",
        "Carpenter": "Carpenter",
        "Iron steel contractor": "Iron steel contractor",
        "Wood and laminate flooring supplier": "Wood and laminate flooring supplier",
        "Aluminum supplier": "Aluminum supplier",
        "Lumber store": "Lumber store",
        "Waterproofing service": "Waterproofing service",
        "Tool rental service": "Tool rental service",
        "PVC industry": "PVC industry",
        "Plastic fabrication company": "Plastic fabrication company",
        "Remodeler": "Remodeler",
        "Insulation contractor": "Insulation contractor",
        "Screen printing supply store": "Screen printing supply store",
        "Painting": "Painting",
        "Kitchen remodeler": "Kitchen remodeler",
        "Flooring contractor": "Flooring contractor",
        "Logging contractor": "Logging contractor",
        "Asphalt contractor": "Asphalt contractor",
        "Paving contractor": "Paving contractor",
        "Earth works company": "Earth works company",
        "Millwork shop": "Millwork shop",
        "Dry wall supply store": "Dry wall supply store",
        "Architectural designer": "Architectural designer",
        "Stationery wholesaler": "Stationery wholesaler",
        "Dry wall contractor": "Dry wall contractor",
        "Topography company": "Topography company",
        "Custom home builder": "Custom home builder",
        "Renovation contractor": "Renovation contractor",
        "Brick manufacturer": "Brick manufacturer",
        "Wallpaper store": "Wallpaper store",
        "Prefabricated house companies": "Prefabricated house companies",
        "Plywood supplier": "Plywood supplier",
        "Construction machine dealer": "Construction machine dealer",
        "Interior architect office": "Interior architect office",
        "Engineering consultant": "Engineering consultant",
        "Building society": "Building society",
        "Fire protection system supplier": "Fire protection system supplier",
        "Concrete contractor": "Concrete contractor",
        "Road construction machine repair service": "Road construction machine repair service",
        "Plast window store": "Plast window store",
        "Concrete factory": "Concrete factory",
        "Fountain contractor": "Fountain contractor",
        "Curtain supplier and maker": "Curtain supplier and maker",
        "Bricklayer": "Bricklayer",
        "Quarry": "Quarry",
        "Dock builder": "Dock builder",
        "Property maintenance": "Property maintenance",
        "Roofing contractor": "Roofing contractor",
        "Stucco contractor": "Stucco contractor",
        "Deck builder": "Deck builder",
        "Building consultant": "Building consultant",
        "Interior designer": "Interior designer",
        "Builder": "Builder",
        "Fire protection equipment supplier": "Fire protection equipment supplier",
        "Stair contractor": "Stair contractor",
        "Log home builder": "Log home builder",
        "Garage door supplier": "Garage door supplier",
        "Landscape architect": "Landscape architect",
        "Landscaper": "Landscaper",
        "Tree service": "Tree service",
        "Portable building manufacturer": "Portable building manufacturer",
        "Window supplier": "Window supplier",
        "PVC windows supplier": "PVC windows supplier",
        "Door shop": "Door shop",
        "Interior door shop": "Interior door shop",
        "Door manufacturer": "Door manufacturer",
        "Door supplier": "Door supplier",
        "Fireplace store": "Fireplace store",
        "Crane dealer": "Crane dealer",
        "Cabinet maker": "Cabinet maker",
        "Cabinet store": "Cabinet store",
        "Handyman/Handywoman/Handyperson": "Handyman/Handywoman/Handyperson",
        "Shopfitter": "Shopfitter",
        "Structural engineer": "Structural engineer",
        "HVAC contractor": "HVAC contractor",
        "Heating contractor": "Heating contractor",
        "Plumber": "Plumber",
        "Landscape designer": "Landscape designer",
        "Surveyor": "Surveyor",
        "Land surveyor": "Land surveyor",
        "Sanitation service": "Sanitation service",
        "Boiler manufacturer": "Boiler manufacturer",
        "Bridge": "Bridge",
        "Screen printer": "Screen printer",
        "Commercial printer": "Commercial printer",
        "Diesel engine repair service": "Diesel engine repair service",
        "Fence contractor": "Fence contractor",
        "Marble contractor": "Marble contractor",
        "Sheet metal contractor": "Sheet metal contractor",
        "Welder": "Welder",
        "Painter": "Painter",
        "Skylight contractor": "Skylight contractor",
        "Drilling contractor": "Drilling contractor",
        "Water damage restoration service": "Water damage restoration service",
        "Land surveying office": "Land surveying office",
        "Building inspector": "Building inspector",
        "Hydraulic equipment supplier": "Hydraulic equipment supplier",
        "Stone supplier": "Stone supplier",
        "Glazier": "Glazier",
        "Glass repair service": "Glass repair service",
        "Cleaning products supplier": "Cleaning products supplier",
        "Fertilizer supplier": "Fertilizer supplier",
        "Small appliance repair service": "Small appliance repair service",
        "Interior Decorator": "Interior Decorator",
        "Construction machine rental service": "Construction machine rental service",
        "Wood floor installation service": "Wood floor installation service",
        "Excavating contractor": "Excavating contractor",
        "Bathroom remodeler": "Bathroom remodeler",
        "Trade fair construction company": "Trade fair construction company",
        "Railing contractor": "Railing contractor",
        "Gravel plant": "Gravel plant",
        "Sandblasting service": "Sandblasting service",
        "Powder coating service": "Powder coating service",
        "Home inspector": "Home inspector",
        "Lawn sprinkler system contractor": "Lawn sprinkler system contractor",
        "Mechanical contractor": "Mechanical contractor",
        "Interior fitting contractor": "Interior fitting contractor",
        "Modular home builder": "Modular home builder"
    },
    "Healthcare": {
        "Private hospital": "Private hospital",
        "Maternity hospital": "Maternity hospital",
        "Hospital": "Hospital",
        "General hospital": "General hospital",
        "Pharmacy": "Pharmacy",
        "Medical group": "Medical group",
        "Medical supply store": "Medical supply store",
        "Association / Organization": "Association / Organization",
        "Non-profit organization": "Non-profit organization",
        "Maternity store": "Maternity store",
        "Pregnancy care center": "Pregnancy care center",
        "University hospital": "University hospital",
        "Health and beauty shop": "Health and beauty shop",
        "Midwife": "Midwife",
        "Department store": "Department store", 
        "Fertility clinic": "Fertility clinic",
        "Reproductive health clinic": "Reproductive health clinic",
        "Women's health clinic": "Women's health clinic",
        "Community health centre": "Community health centre",
        "Volunteer organization": "Volunteer organization",
        "Delivery Service": "Delivery Service",
        "Homeopathic pharmacy": "Homeopathic pharmacy",
        "Herbal medicine store": "Herbal medicine store",
        "Nutritionist": "Nutritionist",
        "Medical equipment supplier": "Medical equipment supplier",
        "Home health care service": "Home health care service",
        "Parapharmacy": "Parapharmacy",
        "Obstetrician-gynecologist": "Obstetrician-gynecologist",
        "Health consultant": "Health consultant",
        "Cosmetics wholesaler": "Cosmetics wholesaler",
        "Medical clinic": "Medical clinic",
        "Medical Center": "Medical Center",
        "Government hospital": "Government hospital",
        "Faculty of pharmacy": "Faculty of pharmacy",
        "Pharmaceutical wholesaler": "Pharmaceutical wholesaler",
        "Surgical products wholesaler": "Surgical products wholesaler",
        "Surgical supply store": "Surgical supply store",
        "Medical equipment manufacturer": "Medical equipment manufacturer",
        "Dental laboratory": "Dental laboratory",
        "Diagnostic center": "Diagnostic center",
        "Laboratory": "Laboratory",
        "Pharmaceutical products wholesaler": "Pharmaceutical products wholesaler",
        "Pharmaceutical lab": "Pharmaceutical lab",
        "Medical technology manufacturer": "Medical technology manufacturer",
        "Dietitian": "Dietitian",
        "Occupational safety and health": "Occupational safety and health",
        "Facial spa": "Facial spa",
        "Spa": "Spa",
        "Weight loss service": "Weight loss service",
        "Beauty salon": "Beauty salon",
        "Make-up artist": "Make-up artist",
        "Ambulance service": "Ambulance service",
        "Permanent make-up clinic": "Permanent make-up clinic"
    },
    "Education, Training & Non-profit": {
        "School": "School",
        "E-learning provider": "E-learning provider",
        "Art school": "Art school",
        "Non-profit organization": "Non-profit organization",
        "Cooking class": "Cooking class",
        "Learning center": "Learning center",
        "University": "University",
        "College": "College",
        "Adult education school": "Adult education school",
        "Training centre": "Training centre",
        "Public university": "Public university",
        "Research foundation": "Research foundation",
        "Educational institution": "Educational institution",
        "Trade school": "Trade school",
        "Non-governmental organization": "Non-governmental organization",
        "Bridge club": "Bridge club",
        "Computer training school": "Computer training school",
        "Senior high school": "Senior high school",
        "Engineering school": "Engineering school",
        "Design institute": "Design institute",
        "Academic department": "Academic department",
        "Software training institute": "Software training institute",
        "Education center": "Education center",
        "Cultural association": "Cultural association",
        "Ecologists association": "Ecologists association",
        "Private university": "Private university"
    },
    "Electrical & Electronics": {
        "Electrical products wholesaler": "Electrical products wholesaler",
        "Electrical equipment supplier": "Electrical equipment supplier",
        "Electrical engineer": "Electrical engineer",
        "Hardware manufacturer": "Hardware manufacturer",
        "Semiconductor manufacturer": "Semiconductor manufacturer",
        "Telecommunications equipment supplier": "Telecommunications equipment supplier",
        "Telecommunications service provider": "Telecommunications service provider",
        "Telecommunications contractor": "Telecommunications contractor",
        "Cable company": "Cable company",
        "Security system supplier": "Security system supplier",
        "Electrical appliance wholesaler": "Electrical appliance wholesaler",
        "Electrical supply store": "Electrical supply store",
        "Electronics wholesaler": "Electronics wholesaler",
        "Electronics store": "Electronics store",
        "Computer store": "Computer store",
        "Locks supplier": "Locks supplier",
        "Electronics company": "Electronics company",
        "Electronic parts supplier": "Electronic parts supplier",
        "Electronics manufacturer": "Electronics manufacturer",
        "Electronics vending machine": "Electronics vending machine",
        "Electrician": "Electrician",
        "Electrical installation service": "Electrical installation service",
        "Electric motor scooter dealer": "Electric motor scooter dealer",
        "Electric motor repair shop": "Electric motor repair shop",
        "Telephone company": "Telephone company",
        "Air conditioning contractor": "Air conditioning contractor",
        "Air conditioning system supplier": "Air conditioning system supplier",
        "Air conditioning repair service": "Air conditioning repair service",
        "Air conditioning store": "Air conditioning store",
        "Computer hardware manufacturer": "Computer hardware manufacturer",
        "Electronics engineer": "Electronics engineer",
        "Electronic engineering service": "Electronic engineering service",
        "Auto electrical service": "Auto electrical service",
        "Electric vehicle charging station": "Electric vehicle charging station",
        "Electric vehicle charging station contractor": "Electric vehicle charging station contractor",
        "Computer networking service": "Computer networking service",
        "Computer service": "Computer service",
        "Phone repair service": "Phone repair service",
        "Stereo repair service": "Stereo repair service",
        "Computer wholesaler": "Computer wholesaler",
        "Computer accessories store": "Computer accessories store",
        "Copier repair service": "Copier repair service",
        "Semi conductor supplier": "Semi conductor supplier",
        "X-ray equipment supplier": "X-ray equipment supplier",
        "Internet service provider": "Internet service provider"
    },
    "Energy, Environment & Resources": {
        "Oil refinery": "Oil refinery",
        "Gas company": "Gas company",
        "Gas station": "Gas station",
        "Oil & natural gas company": "Oil & natural gas company",
        "Oil field equipment supplier": "Oil field equipment supplier",
        "Oil wholesaler": "Oil wholesaler",
        "Diesel fuel supplier": "Diesel fuel supplier",
        "Oil store": "Oil store",
        "Oilfield": "Oilfield",
        "Solar energy company": "Solar energy company",
        "Solar energy system service": "Solar energy system service",
        "Solar energy equipment supplier": "Solar energy equipment supplier",
        "Solar hot water system supplier": "Solar hot water system supplier",
        "Electric utility company": "Electric utility company",
        "Power station": "Power station",
        "Energy equipment and solutions": "Energy equipment and solutions",
        "Coal mining": "Coal mining",
        "Coal processing": "Coal processing",
        "Wind energy company": "Wind energy company",
        "Hydropower plant": "Hydropower plant",
        "Diesel engine dealer": "Diesel engine dealer",
        "Forestry service": "Forestry service",
        "Thermal power plant": "Thermal power plant",
        "Green energy supplier": "Green energy supplier",
        "Nuclear power company": "Nuclear power company",
        "Solar photovoltaic power plant": "Solar photovoltaic power plant",
        "Solid fuel company": "Solid fuel company",
        "Waste management service": "Waste management service",
        "Sewage disposal service": "Sewage disposal service",
        "Recycling center": "Recycling center",
        "Wind farm": "Wind farm",
        "Energy supplier": "Energy supplier",
        "Recycling drop-off location": "Recycling drop-off location",
        "Garbage dump": "Garbage dump",
        "Water utility company": "Water utility company",
        "Water treatment plant": "Water treatment plant",
        "Hydroelectric power plant": "Hydroelectric power plant",
        "Sewage treatment plant": "Sewage treatment plant",
        "Drainage service": "Drainage service",
        "Oil and gas exploration service": "Oil and gas exploration service",
        "Heating oil supplier": "Heating oil supplier",
        "Propane supplier": "Propane supplier",
        "Garbage collection service": "Garbage collection service",
        "Dumpster rental service": "Dumpster rental service"
    },
    "IT & Internet": {
        "Software company": "Software company",
        "IT services provider": "IT services provider",
        "E-commerce platform": "E-commerce platform",
        "Cybersecurity firm": "Cybersecurity firm",
        "AI solutions provider": "AI solutions provider",
        "E-commerce service": "E-commerce service",
        "Scientific equipment supplier": "Scientific equipment supplier",
        "Technology park": "Technology park",
        "Computers": "Computers",
        "Internet shop": "Internet shop"
    },
    "Leisure & Tourism": {
        "TV broadcaster": "TV broadcaster",
        "Film production company": "Film production company",
        "Music label": "Music label",
        "Game developer": "Game developer",
        "Creative agency": "Creative agency",
        "Performing arts theater": "Performing arts theater",
        "Entertainer": "Entertainer",
        "Pottery classes": "Pottery classes",
        "Museum": "Museum",
        "Gym": "Gym",
        "Ski rental service": "Ski rental service",
        "Brewery": "Brewery",
        "Brewpub": "Brewpub",
        "Cafe": "Cafe",
        "Restaurant": "Restaurant",
        "Arts and crafts": "Arts and crafts",
        "Art studio": "Art studio",
        "Art center": "Art center",
        "Art gallery": "Art gallery",
        "Artistic handicrafts": "Artistic handicrafts",
        "Live music bar": "Live music bar",
        "Live music venue": "Live music venue",
        "Event technology service": "Event technology service",
        "Event management company": "Event management company",
        "Cruise agency": "Cruise agency",
        "Tour agency": "Tour agency",
        "Tour operator": "Tour operator",
        "Travel agency": "Travel agency",
        "Cultural center": "Cultural center",
        "Sports complex": "Sports complex",
        "Sportswear store": "Sportswear store",
        "Sports nutrition store": "Sports nutrition store",
        "Sports club": "Sports club",
        "Golf shop": "Golf shop",
        "Martial arts supply store": "Martial arts supply store",
        "Skateboard shop": "Skateboard shop",
        "Skate shop": "Skate shop",
        "Ski shop": "Ski shop",
        "Snowboard shop": "Snowboard shop",
        "Outdoor sports store": "Outdoor sports store",
        "Dance store": "Dance store",
        "Bicycle Shop": "Bicycle Shop",
        "Bicycle wholesaler": "Bicycle wholesaler",
        "Bicycle rental service": "Bicycle rental service",
        "Paintball store": "Paintball store",
        "Club": "Club",
        "Bar": "Bar",
        "Video game store": "Video game store",
        "Souvenir store": "Souvenir store",
        "Function room facility": "Function room facility",
        "Bridal shop": "Bridal shop",
        "Adult entertainment store": "Adult entertainment store",
        "Coffee shop": "Coffee shop",
        "Tea house": "Tea house",
        "Haute French restaurant": "Haute French restaurant",
        "Lebanese restaurant": "Lebanese restaurant",
        "Hamburger restaurant": "Hamburger restaurant",
        "Steak house": "Steak house",
        "Organic restaurant": "Organic restaurant",
        "Festival": "Festival",
        "Bar & grill": "Bar & grill",
        "Bistro": "Bistro",
        "Cafeteria": "Cafeteria",
        "Lunch restaurant": "Lunch restaurant",
        "Sundae restaurant": "Sundae restaurant",
        "Vegetarian restaurant": "Vegetarian restaurant",
        "Western restaurant": "Western restaurant",
        "Chinese restaurant": "Chinese restaurant",
        "Sri Lankan restaurant": "Sri Lankan restaurant",
        "Chophouse restaurant": "Chophouse restaurant",
        "Pizza takeaway": "Pizza takeaway",
        "Delivery Restaurant": "Delivery Restaurant"
    },
    "Manufacturing, Industry, Metal & Engineering": {
        "Industrial equipment supplier": "Industrial equipment supplier",
        "Equipment rental agency": "Equipment rental agency",
        "Manufacturer": "Manufacturer",
        "Rolled metal products supplier": "Rolled metal products supplier",
        "Shipyard": "Shipyard",
        "Shipbuilding and repair company": "Shipbuilding and repair company",
        "Metal processing": "Metal processing",
        "Steel manufacturer": "Steel manufacturer",
        "Car manufacturer": "Car manufacturer",
        "Aerospace company": "Aerospace company",
        "Defense contractor": "Defense contractor",
        "Automation solutions provider": "Automation solutions provider",
        "Machining manufacturer": "Machining manufacturer",
        "Tool manufacturer": "Tool manufacturer",
        "Paint manufacturer": "Paint manufacturer",
        "Auto painting": "Auto painting",
        "Metal workshop": "Metal workshop",
        "Machine shop": "Machine shop",
        "Machinery parts manufacturer": "Machinery parts manufacturer",
        "Toolroom": "Toolroom",
        "Metalwork": "Metalwork",
        "Equipment supplier": "Equipment supplier",
        "Tool store": "Tool store",
        "Tool repair shop": "Tool repair shop",
        "Metal supplier": "Metal supplier",
        "Metal fabricator": "Metal fabricator",
        "Steel fabricator": "Steel fabricator",
        "Metal machinery supplier": "Metal machinery supplier",
        "Foundry": "Foundry",
        "Mechanical plant": "Mechanical plant",
        "Metallurgy company": "Metallurgy company",
        "Laser cutting service": "Laser cutting service",
        "Laser equipment supplier": "Laser equipment supplier",
        "Fastener supplier": "Fastener supplier",
        "Bearing supplier": "Bearing supplier",
        "Pallet supplier": "Pallet supplier",
        "Rubber products supplier": "Rubber products supplier",
        "Glass manufacturer": "Glass manufacturer",
        "Metalware producer": "Metalware producer",
        "Metal working shop": "Metal working shop",
        "Auto parts manufacturer": "Auto parts manufacturer",
        "Auto body parts supplier": "Auto body parts supplier",
        "Aircraft manufacturer": "Aircraft manufacturer",
        "Pottery manufacturer": "Pottery manufacturer",
        "Electronic parts supplier": "Electronic parts supplier",
        "Electronics manufacturer": "Electronics manufacturer",
        "Battery manufacturer": "Battery manufacturer",
        "Siding contractor": "Siding contractor",
        "Machine construction": "Machine construction",
        "Glass blower": "Glass blower",
        "Plastic products supplier": "Plastic products supplier",
        "Wind turbine builder": "Wind turbine builder",
        "Metal finisher": "Metal finisher",
        "Agricultural machinery manufacturer": "Agricultural machinery manufacturer",
        "Appliance repair service": "Appliance repair service",
        "Lamp shade supplier": "Lamp shade supplier",
        "Saddlery": "Saddlery",
        "Sharpening service": "Sharpening service",
        "Amusement machine supplier": "Amusement machine supplier",
        "Engineer": "Engineer",
        "Height works": "Height works",
        "Gardener": "Gardener",
        "Marine surveyor": "Marine surveyor",
        "Quantity surveyor": "Quantity surveyor",
        "Environment renewable natural resources": "Environment renewable natural resources",
        "Iron works": "Iron works",
        "Vending machine supplier": "Vending machine supplier",
        "Ventilating equipment manufacturer": "Ventilating equipment manufacturer",
        "Boat repair shop": "Boat repair shop",
        "Blacksmith": "Blacksmith",
        "Costume jewelry shop": "Costume jewelry shop",
        "E commerce agency": "E commerce agency",
        "Design agency": "Design agency",
        "Appliance parts supplier": "Appliance parts supplier",
        "Pottery store": "Pottery store",
        "Mobile phone repair shop": "Mobile phone repair shop",
        "Computer repair service": "Computer repair service",
        "Antique furniture restoration service": "Antique furniture restoration service",
        "Automation company": "Automation company",
        "Machine workshop": "Machine workshop",
        "Industrial engineer": "Industrial engineer",
        "Mechanical engineer": "Mechanical engineer",
        "Marine engineer": "Marine engineer",
        "Instrumentation engineer": "Instrumentation engineer",
        "Pump supplier": "Pump supplier",
        "Material handling equipment supplier": "Material handling equipment supplier",
        "Lighting store": "Lighting store",
        "Lighting supplier": "Lighting supplier",
        "Furnace repair service": "Furnace repair service",
        "Junkyard": "Junkyard",
        "Auto repair shop": "Auto repair shop",
        "Auto body shop": "Auto body shop",
        "Motorcycle repair shop": "Motorcycle repair shop",
        "Motorcycle parts store": "Motorcycle parts store",
        "Truck dealer": "Truck dealer",
        "Car dealer": "Car dealer",
        "Truck accessories store": "Truck accessories store",
        "Car alarm supplier": "Car alarm supplier",
        "Car repair and maintenance service": "Car repair and maintenance service",
        "Tire shop": "Tire shop",
        "Auto glass shop": "Auto glass shop",
        "Auto glass repair service": "Auto glass repair service",
        "Cash and carry wholesaler": "Cash and carry wholesaler",
        "Flour mill": "Flour mill",
        "Cannery": "Cannery",
        "Beer distributor": "Beer distributor",
        "Beer store": "Beer store",
        "Stamp shop": "Stamp shop",
        "Rubber stamp store": "Rubber stamp store",
        "Copying supply store": "Copying supply store",
        "Screen printing shop": "Screen printing shop",
        "Embroidery service": "Embroidery service",
        "Upholstery shop": "Upholstery shop",
        "Consignment shop": "Consignment shop",
        "Quilt shop": "Quilt shop",
        "Glass industry": "Glass industry",
        "Glass & mirror shop": "Glass & mirror shop",
        "Goldsmith": "Goldsmith",
        "Jeweler": "Jeweler",
        "Jewelry buyer": "Jewelry buyer",
        "Gold dealer": "Gold dealer",
        "Watch store": "Watch store",
        "Safety equipment supplier": "Safety equipment supplier",
        "Sheet metal contractor": "Sheet metal contractor",
        "Plastic products wholesaler": "Plastic products wholesaler",
        "Rubber stamp store": "Rubber stamp store",
        "Diving contractor": "Diving contractor",
        "Laboratory equipment supplier": "Laboratory equipment supplier",
        "Metal processing company": "Metal processing company",
        "Environmental engineer": "Environmental engineer",
        "Machine repair service": "Machine repair service",
        "Tune up supplier": "Tune up supplier",
        "Measuring instruments supplier": "Measuring instruments supplier",
        "Mining equipment": "Mining equipment",
        "Metalware dealer": "Metalware dealer",
        "Wheel store": "Wheel store",
        "Turnery": "Turnery",
        "Auto restoration service": "Auto restoration service",
        "Auto wrecker": "Auto wrecker",
        "Aircraft maintenance company": "Aircraft maintenance company",
        "Shoe factory": "Shoe factory",
        "Leather repair service": "Leather repair service",
        "Leather goods supplier": "Leather goods supplier",
        "Metal services": "Metal services"
    },
    "Minerals": {
        "Mining company": "Mining company",
        "Mineral processing": "Mineral processing"
    },
    "Paper, Printing & Publishing": {
        "Paper mill": "Paper mill",
        "Packaging company": "Packaging company",
        "Printing service": "Printing service",
        "Printing equipment supplier": "Printing equipment supplier",
        "Digital printing service": "Digital printing service",
        "Packaging supply store": "Packaging supply store",
        "Print shop": "Print shop",
        "Trading card store": "Trading card store",
        "Poster store": "Poster store",
        "Toner cartridge supplier": "Toner cartridge supplier",
        "Video duplication service": "Video duplication service",
        "Photo lab": "Photo lab",
        "Magazine store": "Magazine store"
    },
    "Retail & Traders": {
        "Wholesaler": "Wholesaler",
        "Retail chain": "Retail chain",
        "Childrens store": "Childrens store",
        "Consumer electronics retailer": "Consumer electronics retailer",
        "Luxury brand": "Luxury brand",
        "Household products manufacturer": "Household products manufacturer",
        "Bag shop": "Bag shop",
        "Shoe store": "Shoe store",
        "Hobby store": "Hobby store",
        "Painting studio": "Painting studio",
        "Art supply store": "Art supply store",
        "Stationery store": "Stationery store",
        "Paintings store": "Paintings store",
        "Model shop": "Model shop",
        "Steel distributor": "Steel distributor",
        "Pipe supplier": "Pipe supplier",
        "Trading firm": "Trading firm",
        "Store": "Store",
        "Do-it-yourself shop": "Do-it-yourself shop",
        "Book store": "Book store",
        "Craft store": "Craft store",
        "Outlet store": "Outlet store",
        "Handicraft": "Handicraft",
        "Warehouse store": "Warehouse store",
        "Showroom": "Showroom",
        "Furniture store": "Furniture store",
        "Industrial supermarket": "Industrial supermarket",
        "Kitchen furniture store": "Kitchen furniture store",
        "Sofa store": "Sofa store",
        "Bar restaurant furniture store": "Bar restaurant furniture store",
        "Appliance store": "Appliance store",
        "Mattress store": "Mattress store",
        "Bedroom furniture store": "Bedroom furniture store",
        "Outdoor furniture store": "Outdoor furniture store",
        "Used furniture store": "Used furniture store",
        "Furniture rental service": "Furniture rental service",
        "Furniture repair shop": "Furniture repair shop",
        "Furniture wholesaler": "Furniture wholesaler",
        "Garden furniture shop": "Garden furniture shop",
        "Gift wrap store": "Gift wrap store",
        "Shelving store": "Shelving store",
        "School supply store": "School supply store",
        "Office supply store": "Office supply store",
        "Shop supermarket furniture store": "Shop supermarket furniture store",
        "Bedding store": "Bedding store",
        "Mirror shop": "Mirror shop",
        "Safe & vault shop": "Safe & vault shop",
        "Toy manufacturer": "Toy manufacturer",
        "Confectionery store": "Confectionery store",
        "Florist": "Florist",
        "Gift shop": "Gift shop",
        "Sporting goods store": "Sporting goods store",
        "Baby store": "Baby store",
        "Children's clothing store": "Children's clothing store",
        "Home goods store": "Home goods store",
        "Fabric store": "Fabric store",
        "Clothing store": "Clothing store",
        "Baby clothing store": "Baby clothing store",
        "Hypermarket": "Hypermarket",
        "Cosmetics store": "Cosmetics store",
        "Drug store": "Drug store",
        "Leather goods store": "Leather goods store",
        "Handicraft": "Handicraft",
        "Flower delivery": "Flower delivery",
        "Charity": "Charity",
        "Natural goods store": "Natural goods store",
        "Book store": "Book store",
        "Toy store": "Toy store",
        "Religious goods store": "Religious goods store",
        "Shopping mall": "Shopping mall",
        "Store": "Store",
        "Supermarket": "Supermarket",
        "Children's furniture store": "Children's furniture store",
        "Women's clothing store": "Women's clothing store",
        "Embroidery shop": "Embroidery shop",
        "Clothing supplier": "Clothing supplier",
        "Manufacturer": "Manufacturer",
        "Gift shop": "Gift shop",
        "Pet store": "Pet store",
        "Gift basket store": "Gift basket store",
        "Organic food store": "Organic food store",
        "Pet supply store": "Pet supply store",
        "Clothes and fabric manufacturer": "Clothes and fabric manufacturer",
        "Work clothes store": "Work clothes store",
        "Leather goods manufacturer": "Leather goods manufacturer",
        "Furniture manufacturer": "Furniture manufacturer",
        "Furniture maker": "Furniture maker",
        "Clothing wholesaler": "Clothing wholesaler",
        "Fabric wholesaler": "Fabric wholesaler",
        "Sewing machine store": "Sewing machine store",
        "Auto parts store": "Auto parts store",
        "Car accessories store": "Car accessories store",
        "Cell phone store": "Cell phone store",
        "Bicycle Shop": "Bicycle Shop",
        "Outdoor clothing and equipment shop": "Outdoor clothing and equipment shop",
        "Truck repair shop": "Truck repair shop",
        "Vintage clothing store": "Vintage clothing store",
        "Used clothing store": "Used clothing store",
        "Game store": "Game store",
        "Restaurant supply store": "Restaurant supply store",
        "Corporate gift supplier": "Corporate gift supplier",
        "Figurine shop": "Figurine shop",
        "Children's book store": "Children's book store",
        "Battery store": "Battery store",
        "Fashion accessories store": "Fashion accessories store",
        "Audio visual equipment supplier": "Audio visual equipment supplier",
        "Boutique": "Boutique",
        "Outdoor sports store": "Outdoor sports store",
        "Used book store": "Used book store",
        "Market": "Market",
        "Rare book store": "Rare book store",
        "Comic book store": "Comic book store",
        "Clothing wholesale market place": "Clothing wholesale market place",
        "Surf shop": "Surf shop",
        "Camera store": "Camera store",
        "Home audio store": "Home audio store",
        "Wholesale food store": "Wholesale food store",
        "Wine cellar": "Wine cellar",
        "Tea store": "Tea store",
        "Pie shop": "Pie shop",
        "Boot store": "Boot store",
        "Janitorial service": "Janitorial service",
        "Children's store": "Children's store",
        "Paper distributor": "Paper distributor",
        "Sign shop": "Sign shop",
        "Art studio": "Art studio",
        "Bed shop": "Bed shop",
        "Antique furniture store": "Antique furniture store",
        "Silk store": "Silk store",
        "Photo shop": "Photo shop",
        "Record store": "Record store",
        "Ski shop": "Ski shop",
        "Snowboard shop": "Snowboard shop",
        "Auto parts market": "Auto parts market",
        "Used auto parts store": "Used auto parts store",
        "Bicycle wholesaler": "Bicycle wholesaler",
        "Tea exporter": "Tea exporter",
        "Martial arts supply store": "Martial arts supply store",
        "Wholesale florist": "Wholesale florist",
        "Linens store": "Linens store",
        "Promotional products supplier": "Promotional products supplier",
        "Men's clothing store": "Men's clothing store",
        "Thrift store": "Thrift store",
        "Jewelry designer": "Jewelry designer",
        "Jewelry store": "Jewelry store",
        "Clothes and fabric wholesaler": "Clothes and fabric wholesaler",
        "Cell phone accessory store": "Cell phone accessory store",
        "Volkswagen dealer": "Volkswagen dealer",
        "Office equipment supplier": "Office equipment supplier",
        "Leather wholesaler": "Leather wholesaler",
        "Wine wholesaler and importer": "Wine wholesaler and importer",
        "Footwear wholesaler": "Footwear wholesaler",
        "Second hand store": "Second hand store",
        "Custom tailor": "Custom tailor",
        "Religious book store": "Religious book store",
        "Lingerie store": "Lingerie store",
        "T-shirt store": "T-shirt store",
        "Custom t-shirt store": "Custom t-shirt store",
        "Used bicycle shop": "Used bicycle shop",
        "Novelty store": "Novelty store",
        "Souvenir store": "Souvenir store",
        "Convenience store": "Convenience store",
        "Office furniture store": "Office furniture store",
        "Running store": "Running store",
        "Shoe repair shop": "Shoe repair shop",
        "Beauty product supplier": "Beauty product supplier",
        "Beauty supply store": "Beauty supply store",
        "Gun shop": "Gun shop",
        "Rock shop": "Rock shop",
        "Kiosk": "Kiosk",
        "Artist": "Artist",
        "Metaphysical supply store": "Metaphysical supply store",
        "Scale model club": "Scale model club",
        "Airsoft supply store": "Airsoft supply store",
        "Dive shop": "Dive shop",
        "Media company": "Media company",
        "Coffee shop": "Coffee shop",
        "Ice cream shop": "Ice cream shop",
        "Candy store": "Candy store",
        "Farm shop": "Farm shop",
        "Organic shop": "Organic shop",
        "Pet supply store": "Pet supply store",
        "Farmers' market": "Farmers' market",        
        "Farmers market": "Farmers market",
        "Antique store": "Antique store",
        "Lingerie manufacturer": "Lingerie manufacturer",
        "Computer desk store": "Computer desk store",
        "Wholesale market": "Wholesale market",
        "Uniform store": "Uniform store",
        "Beauty products wholesaler": "Beauty products wholesaler",
        "Perfume store": "Perfume store",
        "Exercise equipment store": "Exercise equipment store",
        "Trophy shop": "Trophy shop",
        "Stained glass studio": "Stained glass studio",
        "Cutlery store": "Cutlery store",
        "Costume store": "Costume store",
        "Model train store": "Model train store",
        "Orthopedic shoe store": "Orthopedic shoe store",
        "Grill store": "Grill store",
        "Futon store": "Futon store",
        "Christian book store": "Christian book store",
        "Bait shop": "Bait shop",
        "Army & navy surplus shop": "Army & navy surplus shop",
        "Battery wholesaler": "Battery wholesaler",
        "Office equipment rental service": "Office equipment rental service"
    },
    "Textiles, Clothing, Leather, Watchmaking, Jewellery": {
        "Textile manufacturer": "Textile manufacturer",
        "Clothing store": "Clothing store",
        "Knitwear manufacturer": "Knitwear manufacturer",
        "Sewing shop": "Sewing shop",
        "Sewing company": "Sewing company",
        "Fabric product manufacturer": "Fabric product manufacturer",
        "Textile mill": "Textile mill"
    },
    "Transport & Logistics": {
        "Distribution service": "Distribution service",
        "Shipping company": "Shipping company",
        "Airline": "Airline",
        "Railway operator": "Railway operator",
        "Trucking company": "Trucking company",
        "Warehouse": "Warehouse",
        "Courier service": "Courier service",
        "Logistics service": "Logistics service",
        "Freight forwarding service": "Freight forwarding service",
        "Shipping service": "Shipping service",
        "Towing service": "Towing service"
    },
    "Real Estate": {
        "Real estate developer": "Real estate developer",
        "Real Estate Agency": "Real Estate Agency",
        "Real estate": "Real estate",
        "Condominium complex": "Condominium complex",
        "Apartment complex": "Apartment complex",
        "Lodging": "Lodging",
        "Guest house": "Guest house",
        "Hotel": "Hotel",
        "Real estate attorney": "Real estate attorney",
        "Real estate surveyor": "Real estate surveyor",
        "Commercial real estate agency": "Commercial real estate agency",
        "Real estate agent": "Real estate agent",
        "Home help service agency": "Home help service agency"
    }
}
